package com.myapp.models
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;



@Data
@DynamoDBTable(tableName = "exercise")
@Builder
@NoArgsConstructor
@AllArgsConstructor
class Exercise {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private val id: String? = null

    @DynamoDBAttribute
    private val name: String? = null


}