package com.myapp.models
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;



@Data
@DynamoDBTable(tableName = "exercise")
@Builder
@NoArgsConstructor
@AllArgsConstructor
class Exercise() {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public var id: String? = null

    @DynamoDBAttribute
    public  var levelId: String? = null

    @DynamoDBAttribute
    public var modalityId: String? = null

    @DynamoDBAttribute
    public var name: String? = null


}