package com.myapp.models

import com.amazonaws.services.dynamodbv2.datamodeling.*
import lombok.AllArgsConstructor
import lombok.Builder
import lombok.Data
import lombok.NoArgsConstructor


@Data
@DynamoDBTable(tableName = "level")
@Builder
@NoArgsConstructor
@AllArgsConstructor
class Level {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private val id: String? = null

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private val name: Level? = null


}