package com.myapp.models

import com.amazonaws.services.dynamodbv2.datamodeling.*
import lombok.AllArgsConstructor
import lombok.Builder
import lombok.Data
import lombok.NoArgsConstructor

@Data
@DynamoDBTable(tableName = "modality")
@Builder
@NoArgsConstructor
@AllArgsConstructor
class Modality {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private val id: String? = null

    @DynamoDBAttribute
    private val exerciseId: String? = null

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private val name: Modality? = null

}