package com.myapp.models

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import lombok.AllArgsConstructor
import lombok.Builder
import lombok.Data
import lombok.NoArgsConstructor

@Data
@DynamoDBTable(tableName = "muscle_group")
@Builder
@NoArgsConstructor
@AllArgsConstructor
class MuscleGroup {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public lateinit var id: String

    @DynamoDBAttribute
    public lateinit var exerciseId: String

    @DynamoDBAttribute
    public lateinit var name: String


}