package com.myapp.models

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import lombok.AllArgsConstructor
import lombok.Builder
import lombok.Data
import lombok.NoArgsConstructor

@Data
@DynamoDBTable(tableName = "muscle_group")
@Builder
@NoArgsConstructor
@AllArgsConstructor
class MuscleGroup() {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id: String?=null

//    @DynamoDBAttribute
//     var exerciseId: String?=null
//
//    @DynamoDBAttribute
//    var muscles: List<Muscle?> = emptyList()

    @DynamoDBAttribute
    var name: String?=null
}